---
title: "not working server generated object keys in riak-erlang-client"
description: ""
project: community
lastmod: 2011-05-07T05:47:31-07:00
sitemap:
  priority: 0.2
layout: mailinglistitem
mailinglist_id: "msg03278"
author_name: "Dmitry Rozhkov"
project_section: "mailinglistitem"
sent_date: 2011-05-07T05:47:31-07:00
---


 Hi!

I've just tried to put an object without a key as described in the docs, but
this feature doesn't seem to work (sasl-error.log attached):

==========================================
1&gt; Object = riakc\\_obj:new(&lt;&lt;"boss\\_db\\_test\\_parent\\_models"&gt;&gt;, undefined,
&lt;&lt;"first"&gt;&gt;).
{riakc\\_obj,&lt;&lt;"boss\\_db\\_test\\_parent\\_models"&gt;&gt;,undefined,
 undefined,[],undefined,&lt;&lt;"first"&gt;&gt;}
2&gt; {ok, Conn} = riakc\\_pb\\_socket:start\\_link("testhost", 8087).
{ok,&lt;0.38.0&gt;}
3&gt; riakc\\_pb\\_socket:put(Conn, Object).

=ERROR REPORT==== 7-May-2011::14:34:21 ===
\\*\\* Generic server &lt;0.38.0&gt; terminating
\\*\\* Last message in was {tcp\\_closed,#Port&lt;0.1131&gt;}
\\*\\* When Server state ==
{state,"testhost",8087,false,false,undefined,undefined,
 {[],[]},
 1,[],infinity,100}
\\*\\* Reason for termination ==
\\*\\* disconnected
\\*\\* exception exit: disconnected
==========================================

With a key provided everything works ok.
Can it be a server issue?

BR,
Dmitry
=ERROR REPORT==== 7-May-2011::17:58:31 ===
\\*\\* Generic server &lt;0.27181.1&gt; terminating 
\\*\\* Last message in was {tcp,#Port&lt;0.11652&gt;,
 [11|
 &lt;&lt;10,26,98,111,115,115,95,100,98,95,116,101,115,
 116,95,112,97,114,101,110,116,95,109,111,100,
 101,108,115,34,7,10,5,102,105,114,115,116,56,1&gt;&gt;]}
\\*\\* When Server state == {state,#Port&lt;0.11652&gt;,
 {riak\\_client,'riak@127.0.0.1',&lt;&lt;5,16,190,213&gt;&gt;},
 undefined,undefined}
\\*\\* Reason for termination == 
\\*\\* {function\\_clause,[{riak\\_object,new,
 [&lt;&lt;"boss\\_db\\_test\\_parent\\_models"&gt;&gt;,undefined,
 &lt;&lt;&gt;&gt;]},
 {riak\\_kv\\_pb\\_socket,process\\_message,2},
 {riak\\_kv\\_pb\\_socket,handle\\_info,2},
 {gen\\_server2,handle\\_msg,7},
 {proc\\_lib,init\\_p\\_do\\_apply,3}]}

=CRASH REPORT==== 7-May-2011::17:58:31 ===
 crasher:
 initial call: gen:init\\_it/6
 pid: &lt;0.27181.1&gt;
 registered\\_name: []
 exception exit: {function\\_clause,[{riak\\_object,new,[&lt;&lt;"boss\\_db\\_test\\_parent\\_models"&gt;&gt;,undefined,&lt;&lt;&gt;&gt;]},{riak\\_kv\\_pb\\_socket,process\\_message,2},{riak\\_kv\\_pb\\_socket,handle\\_info,2},{gen\\_server2,handle\\_msg,7},{proc\\_lib,init\\_p\\_do\\_apply,3}]}
 in function gen\\_server2:terminate/6
 in call from proc\\_lib:init\\_p\\_do\\_apply/3
 ancestors: [riak\\_kv\\_pb\\_socket\\_sup,riak\\_kv\\_sup,&lt;0.134.0&gt;]
 messages: []
 links: [&lt;0.137.0&gt;,#Port&lt;0.11652&gt;]
 dictionary: []
 trap\\_exit: false
 status: running
 heap\\_size: 233
 stack\\_size: 24
 reductions: 443
 neighbours:

=SUPERVISOR REPORT==== 7-May-2011::17:58:31 ===
 Supervisor: {local,riak\\_kv\\_pb\\_socket\\_sup}
 Context: child\\_terminated
 Reason: {function\\_clause,[{riak\\_object,new,[&lt;&lt;"boss\\_db\\_test\\_parent\\_models"&gt;&gt;,undefined,&lt;&lt;&gt;&gt;]},{riak\\_kv\\_pb\\_socket,process\\_message,2},{riak\\_kv\\_pb\\_socket,handle\\_info,2},{gen\\_server2,handle\\_msg,7},{proc\\_lib,init\\_p\\_do\\_apply,3}]}
 Offender: [{pid,&lt;0.27181.1&gt;},{name,undefined},{mfa,{riak\\_kv\\_pb\\_socket,start\\_link,[]}},{restart\\_type,temporary},{shutdown,brutal\\_kill},{child\\_type,worker}]

\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_
riak-users mailing list
riak-users@lists.basho.com
http://lists.basho.com/mailman/listinfo/riak-users\\_lists.basho.com

