---
title: "Re: Riak 1.3.1 refusing to start up"
description: ""
project: community
lastmod: 2013-04-24T02:52:57-07:00
sitemap:
  priority: 0.2
layout: mailinglistitem
mailinglist_id: "msg10959"
mailinglist_parent_id: "msg10958"
author_name: "Eric Redmond"
project_section: "mailinglistitem"
sent_date: 2013-04-24T02:52:57-07:00
---


This commonly happens if a node name or IP has changed args.vm -name without 
notifying the ring. Either use the riak-admin cluster replaced command, or 
delete the ring directory and rejoin the cluster.

Note this isn't the only reason for missing capabilities, but a very common one.

Sent from my iPhone

On Apr 24, 2013, at 11:11 AM, Chris Read  wrote:

&gt; Greetings all...
&gt; 
&gt; I've got a riak cluster that's now refusing to start. We're running version 
&gt; 1.3.1 on 3 nodes, all of them fail to start with the following error in 
&gt; console.log:
&gt; 
&gt; 2013-04-24 04:05:15.518 [error] &lt;0.152.0&gt; gen\\_server riak\\_core\\_capability 
&gt; terminated with reason: no function clause matching orddict:fetch(riak@in, 
&gt; []) line 72
&gt; 2013-04-24 04:05:15.522 [error] &lt;0.152.0&gt; CRASH REPORT Process 
&gt; riak\\_core\\_capability with 0 neighbours exited with reason: no function clause 
&gt; matching orddict:fetch(riak@in, []) line 72 in gen\\_server:terminate/6 line 747
&gt; 2013-04-24 04:05:15.527 [error] &lt;0.133.0&gt; Supervisor riak\\_core\\_sup had child 
&gt; riak\\_core\\_capability started with riak\\_core\\_capability:start\\_link() at 
&gt; &lt;0.152.0&gt; exit with reason no function clause matching orddict:fetch(riak@in, 
&gt; []) line 72 in context child\\_terminated
&gt; 2013-04-24 04:05:15.529 [error] &lt;0.131.0&gt; CRASH REPORT Process &lt;0.131.0&gt; with 
&gt; 0 neighbours exited with reason: 
&gt; {{function\\_clause,[{orddict,fetch,[riak@in,[]],[{file,"orddict.erl"},{line,72}]},{riak\\_core\\_capability,renegotiate\\_capabilities,1,[{file,"src/riak\\_core\\_capability.erl"},{line,415}]},{riak\\_core\\_capability,handle\\_call,3,[{file,"src/riak\\_core\\_capability.erl"},{line,208}]},{gen\\_server,handle\\_msg,5,[{file,"gen\\_server.erl"},{line,588}]},{proc\\_lib,init\\_p\\_do\\_apply,3,[{file,"proc\\_lib.erl"},{line,227}]}]},{gen\\_server,call,[riak\\_core\\_capability,{register,{riak\\_core,vnode\\_routing},{capability,[proxy,legacy],...}},...]}}
&gt; in application\\_master:init/4 line 138
&gt; 2013-04-24 04:05:15.531 [info] &lt;0.7.0&gt; Application riak\\_core exited with 
&gt; reason: 
&gt; {{function\\_clause,[{orddict,fetch,[riak@in,[]],[{file,"orddict.erl"},{line,72}]},{riak\\_core\\_capability,renegotiate\\_capabilities,1,[{file,"src/riak\\_core\\_capability.erl"},{line,415}]},{riak\\_core\\_capability,handle\\_call,3,[{file,"src/riak\\_core\\_capability.erl"},{line,208}]},{gen\\_server,handle\\_msg,5,[{file,"gen\\_server.erl"},{line,588}]},{proc\\_lib,init\\_p\\_do\\_apply,3,[{file,"proc\\_lib.erl"},{line,227}]}]},{gen\\_server,call,[riak\\_core\\_capability,{register,{riak\\_core,vnode\\_routing},{capability,[proxy,legacy],...}},...]}}
&gt; 
&gt; Any ideas?
&gt; 
&gt; Chris
&gt; \\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_
&gt; riak-users mailing list
&gt; riak-users@lists.basho.com
&gt; http://lists.basho.com/mailman/listinfo/riak-users\\_lists.basho.com

\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_
riak-users mailing list
riak-users@lists.basho.com
http://lists.basho.com/mailman/listinfo/riak-users\\_lists.basho.com

