---
title: "Python library: Error with counters"
description: ""
project: community
lastmod: 2014-08-15T09:13:22-07:00
sitemap:
  priority: 0.2
layout: mailinglistitem
mailinglist_id: "msg14667"
author_name: "Alex De la rosa"
project_section: "mailinglistitem"
sent_date: 2014-08-15T09:13:22-07:00
---


Hi there,

I created a "counter" bucket called "likes" with the following shell script:

riak-admin bucket-type create likes '{"props":{"datatype":"counter"}}'

When I try to follow the guide [
http://docs.basho.com/riak/2.0.0/dev/using/data-types ] to use this bucket
with Python, I found the following issue:

Traceback (most recent call last):
 File "x.py", line 17, in 
 bucket = client.bucket\\_type('counter\\_bucket').bucket('likes')
AttributeError: 'RiakClient' object has no attribute 'bucket\\_type'

Something wrong? Is a fresh install from "pip" so I thought the Python
library would be in its last updated version?

Thanks!
Alex
\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_
riak-users mailing list
riak-users@lists.basho.com
http://lists.basho.com/mailman/listinfo/riak-users\\_lists.basho.com

