---
title: "restore"
description: ""
project: community
lastmod: 2012-04-07T23:41:00-07:00
sitemap:
  priority: 0.2
layout: mailinglistitem
mailinglist_id: "msg07175"
author_name: "gibraltar"
project_section: "mailinglistitem"
sent_date: 2012-04-07T23:41:00-07:00

---



hi,

I am trying to transfer data from my local machine to a server using 
backup/restore operation. 

$ sudo riak-admin restore riak@10.196.187.80 riak /home/ec2-user/geodata.bck

Above command generates following error message. Seems like permission error, 
however I execute the command with sudo. I did chown to 'riak' but made no 
difference. Any idea why?

Attempting to restart script through sudo -u riak
Restoring from '/home/ec2-user/geodata.bck' to cluster to which 
'riak@10.196.187.80' belongs.
{"init terminating in 
do\_boot",{{badmatch,{error,{file\_error,"/home/ec2-user/geodata.bck",eacces}}},[{riak\_kv\_backup,restore,2},{erl\_eval,do\_apply,5},{init,start\_it,1},{init,start\_em,1}]}}
init terminating in do\_boot ()


thanks,
gibraltar\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
riak-users mailing list
riak-users@lists.basho.com
http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com

