---
title: "Re: Quick Q re: error"
description: ""
project: community
lastmod: 2012-11-09T09:10:17-08:00
sitemap:
  priority: 0.2
layout: mailinglistitem
mailinglist_id: "msg09263"
mailinglist_parent_id: "msg09258"
author_name: "Sean Cribbs"
project_section: "mailinglistitem"
sent_date: 2012-11-09T09:10:17-08:00
---


Well, it's pretty obvious that it simply can't connect, especially
since your configuration is the default -- which means HTTP pointed to
127.0.0.1:8098. Is your Riak node running and on that port? Can you
hit it from curl on the command line?

On Fri, Nov 9, 2012 at 7:36 AM, Martin Streicher
 wrote:
>
> I'm not doing anything special in Riak::Client.
>
> How can I narrow what the RuntimeError is?
>
>
>
> On Nov 9, 2012, at 10:21 AM, Sean Cribbs wrote:
>
>> Martin,
>>
>> How is your Riak::Client object configured? That looks like one of two
>> possibilities: first, the request failed 3 times in a row; second, one
>> of the backends is raising an exception that seems network related but
>> isn't one of the standard network errors (i.e it's a RuntimeError, but
>> it should be a SystemError with econnrefused errno!).
>>
>> On Fri, Nov 9, 2012 at 7:12 AM, Martin Streicher
>>  wrote:
>>>
>>> I get a connection refused error when I try to enable search from my code.
>>>
>>> /var/www/zutron/shared/bundle/ruby/1.9.1/gems/riak-client-1.0.5/lib/riak/client.rb:450:in
>>> `rescue in recover\_from': Connection refused - connect(2) (RuntimeError)
>>> from 
>>> /var/www/zutron/shared/bundle/ruby/1.9.1/gems/riak-client-1.0.5/lib/riak/client.rb:422:in
>>> `recover\_from'
>>> from 
>>> /var/www/zutron/shared/bundle/ruby/1.9.1/gems/riak-client-1.0.5/lib/riak/client.rb:284:in
>>> `http'
>>> from 
>>> /var/www/zutron/shared/bundle/ruby/1.9.1/gems/riak-client-1.0.5/lib/riak/client.rb:129:in
>>> `backend'
>>> from 
>>> /var/www/zutron/shared/bundle/ruby/1.9.1/gems/riak-client-1.0.5/lib/riak/client.rb:246:in
>>> `get\_bucket\_props'
>>> from 
>>> /var/www/zutron/shared/bundle/ruby/1.9.1/gems/riak-client-1.0.5/lib/riak/bucket.rb:77:in
>>> `props'
>>> from 
>>> /var/www/zutron/shared/bundle/ruby/1.9.1/gems/riak-client-1.0.5/lib/riak/bucket.rb:68:in
>>> `props='
>>> from 
>>> /var/www/zutron/releases/20121108191450/lib/classes/riak\_search.rb:6:in 
>>> `enable\_search'
>>>
>>> enable\_search is:
>>>
>>> def self.enable\_search(bucket\_name, client = Riak::Client.new)
>>> bucket = client.bucket bucket\_name
>>> bucket.props = {search: true}
>>> end
>>>
>>> Any ideas why it's failing? Search is enabled on the machine.
>>>
>>>
>>>
>>>
>>> \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
>>> riak-users mailing list
>>> riak-users@lists.basho.com
>>> http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com
>>
>>
>>
>> --
>> Sean Cribbs 
>> Software Engineer
>> Basho Technologies, Inc.
>> http://basho.com/
>



-- 
Sean Cribbs 
Software Engineer
Basho Technologies, Inc.
http://basho.com/

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
riak-users mailing list
riak-users@lists.basho.com
http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com

