---
title: "Re: Python Client Thread Safe?"
description: ""
project: community
lastmod: 2012-02-27T19:47:14-08:00
sitemap:
  priority: 0.2
layout: mailinglistitem
mailinglist_id: "msg06770"
mailinglist_parent_id: "msg06769"
author_name: "Greg Stein"
project_section: "mailinglistitem"
sent_date: 2012-02-27T19:47:14-08:00
---


To clarify my thread-sharing comments: those are with respect to the
unreleased client. And I've checked: the Bucket objects are sharable,
too. Obviously, not if multiple threads are calling competing .set\\_r()
or somesuch on the client or bucket. The short answer is share Client
and Bucket objects to get access to Objects, and keep those
per-thread.

The underlying transport will manage multiple connections,
persistently, in a thread-safe manner.

(and I'm unclear on threading issues for the 1.3.0 python client)

Cheers,
-g

On Mon, Feb 27, 2012 at 22:37, Greg Stein  wrote:
&gt; IIRC, that error was seen when connecting to Riak 0.14.0. What version of
&gt; Riak are you connecting to?
&gt;
&gt; I might also suggest using the current, unreleased Python client from the
&gt; master branch on GitHub. It has much better support for threads and
&gt; persistent connections. Just don't use variant client\\_id values and PB
&gt; connections (switch to Riak 1.1 and ignore client\\_id).
&gt;
&gt; One Client can be shared across threads, but not Objects. I don't recall
&gt; whether Buckets can be shared.
&gt;
&gt; Cheers,
&gt; -g
&gt;
&gt; On Feb 26, 2012 2:39 PM, "Jim Adler"  wrote:
&gt;&gt;
&gt;&gt; I'm getting the following error while using protocol buffers
&gt;&gt; (RiakPbcTransport) with more than one thread (stack trace below):
&gt;&gt;
&gt;&gt;        Socket returned short packet length 0 - expected 4'
&gt;&gt;
&gt;&gt; I'm using the 1.3.0 Python client on Mac and Ubuntu 11.04 and have seen
&gt;&gt; the same error on both OS's. A single-thread works fine as does the
&gt;&gt; RiakHttpTransport.
&gt;&gt;
&gt;&gt; Anyone have this problem?
&gt;&gt;
&gt;&gt; Thanks,
&gt;&gt; Jim
&gt;&gt;
&gt;&gt; File
&gt;&gt;
&gt;&gt; "/usr/local/Cellar/python/2.7.2/Frameworks/Python.framework/Versions/2.7/li
&gt;&gt; b/python2.7/site-packages/riak-1.3.0-py2.7.egg/riak/bucket.py", line 260,
&gt;&gt; in get
&gt;&gt;    return obj.reload(r)
&gt;&gt;  File
&gt;&gt;
&gt;&gt; "/usr/local/Cellar/python/2.7.2/Frameworks/Python.framework/Versions/2.7/li
&gt;&gt; b/python2.7/site-packages/riak-1.3.0-py2.7.egg/riak/riak\\_object.py", line
&gt;&gt; 373, in reload
&gt;&gt;    Result = t.get(self, r, vtag)
&gt;&gt;  File
&gt;&gt;
&gt;&gt; "/usr/local/Cellar/python/2.7.2/Frameworks/Python.framework/Versions/2.7/li
&gt;&gt; b/python2.7/site-packages/riak-1.3.0-py2.7.egg/riak/transports/pbc.py",
&gt;&gt; line 195, in get
&gt;&gt;    msg\\_code, resp = self.send\\_msg(MSG\\_CODE\\_GET\\_REQ, req, None)
&gt;&gt;  File
&gt;&gt;
&gt;&gt; "/usr/local/Cellar/python/2.7.2/Frameworks/Python.framework/Versions/2.7/li
&gt;&gt; b/python2.7/site-packages/riak-1.3.0-py2.7.egg/riak/transports/pbc.py",
&gt;&gt; line 387, in send\\_msg
&gt;&gt;    return self.recv\\_msg(conn, expect)
&gt;&gt;  File
&gt;&gt;
&gt;&gt; "/usr/local/Cellar/python/2.7.2/Frameworks/Python.framework/Versions/2.7/li
&gt;&gt; b/python2.7/site-packages/riak-1.3.0-py2.7.egg/riak/transports/pbc.py",
&gt;&gt; line 413, in recv\\_msg
&gt;&gt;    self.recv\\_pkt(conn)
&gt;&gt;  File
&gt;&gt;
&gt;&gt; "/usr/local/Cellar/python/2.7.2/Frameworks/Python.framework/Versions/2.7/li
&gt;&gt; b/python2.7/site-packages/riak-1.3.0-py2.7.egg/riak/transports/pbc.py",
&gt;&gt; line 460, in recv\\_pkt
&gt;&gt;    len(nmsglen))
&gt;&gt; RiakError: 'Socket returned short packet length 0 - expected 4'
&gt;&gt;

